## Numpy 矩阵计算 -- 模块 linalg 的常用函数

## 线性代数

Numpy 中的模块 `numpy.linalg` 提供了很多线性代数中的函数，如矩阵求逆、求特征值与特征向量、计算行列式、矩阵条件数以及求解解线性方程组等。

In [2]:
import numpy as np

## 矩阵计算

- 创建矩阵

In [3]:
A = np.mat('0 1 2;1 2 3;3 2 1')
A

matrix([[0, 1, 2],
        [1, 2, 3],
        [3, 2, 1]])

- 使用 inv 函数计算逆矩阵

In [4]:
A_inv = np.linalg.inv(A)
A_inv

matrix([[ 2.45650889e+15, -1.84238167e+15,  6.14127222e+14],
        [-4.91301778e+15,  3.68476333e+15, -1.22825444e+15],
        [ 2.45650889e+15, -1.84238167e+15,  6.14127222e+14]])

## 求解线性方程组

https://www.tutorialspoint.com/numpy/numpy_inv.htm

In [5]:
# Column vector b
b1 = np.array([[6],[-1],[2]]) 
b1 

array([[ 6],
       [-1],
       [ 2]])

In [6]:
# x1 = A^-1 b1
x1 = np.dot(A_inv, b1)
x1

matrix([[ 1.78096894e+16],
        [-3.56193789e+16],
        [ 1.78096894e+16]])

In [7]:
b2 = np.array([[6],[-1],[2.0001]]) 
b2 

array([[ 6.    ],
       [-1.    ],
       [ 2.0001]])

In [8]:
# x2 = A^-1 b2
x2 = np.dot(A_inv, b2)
x2

matrix([[ 1.78097508e+16],
        [-3.56195017e+16],
        [ 1.78097508e+16]])

- 或者用矩阵乘法 @

In [10]:
A_inv @ b2

matrix([[ 1.78097508e+16],
        [-3.56195017e+16],
        [ 1.78097508e+16]])

- 矩阵的条件数

In [9]:
np.linalg.cond(A)

1.4986581371025982e+16

- `numpy.linalg` 中的函数 `solve` 可以直接求解形如 `Ax = b` 的线性方程组，其中 `A` 为矩阵，`b` 为列向量或矩阵（即多个列向量），`x` 为待求的未知量。

In [14]:
x3 = np.linalg.solve(A, b1) 
x3

array([[ 1.78096894e+16],
       [-3.56193789e+16],
       [ 1.78096894e+16]])

## 计算行列式

In [15]:
#  Compute the determinant of an array
A_det = np.linalg.det(A)
A_det

-1.6283271027835654e-15

In [16]:
A_inv_det = np.linalg.det(A_inv)
A_inv_det

-642042095637530.5

In [17]:
A_det*A_inv_det

1.045454545454549

## 矩阵的秩和迹

In [63]:
# Rank of a matrix
print("Rank of A:", np.linalg.matrix_rank(A))

# Trace of matrix A
print("\nTrace of A:", np.trace(A))

Rank of A: 2

Trace of A: 3


In [68]:
a, u = np.linalg.eig(A)

In [69]:
a

array([ 5.14005494e+00, -2.14005494e+00, -2.64981292e-16])

In [70]:
u

matrix([[-0.37305822, -0.50528836,  0.40824829],
        [-0.70028651, -0.42299457, -0.81649658],
        [-0.60862663,  0.75216971,  0.40824829]])

- 验证 $Au = \lambda u$

In [75]:
A @ u[:,0]

matrix([[-1.91753976],
        [-3.59951112],
        [-3.12837431]])

In [76]:
a[0]*u[:,0]

matrix([[-1.91753976],
        [-3.59951112],
        [-3.12837431]])

## 矩阵范数

In [13]:
from numpy import linalg as LA

x_norm=np.linalg.norm(x, ord=None, axis=None, keepdims=False)

#### 计算矩阵或向量范数。

此函数根据 `ord` 参数的值上返回 8 个矩阵范数之一，或无数个向量范数之一。

|ord | norm for matrices |            norm for vectors|
|:-|:-:|-:|
|None  | Frobenius norm    |            2-norm|
|'fro' | Frobenius norm    |            --|
|'nuc' | nuclear norm      |            --|
|inf   | max(sum(abs(x), axis=1))  |    max(abs(x)) |
|-inf  | min(sum(abs(x), axis=1))  |    min(abs(x)) |
|0     | --                        |    sum(x != 0) |
|1     | max(sum(abs(x), axis=0))  |    as below    |
|-1    | min(sum(abs(x), axis=0))  |    as below    |
|2     | 2-norm (largest sing. value)|  as below    |
|-2    | smallest singular value   |    as below    |
|other | --                        |    sum(abs(x)\*\*ord)\*\*(1./ord)|

- 向量范数

In [20]:
a = np.arange(5) - 2
a

array([-2, -1,  0,  1,  2])

In [21]:
LA.norm(a)

3.1622776601683795

In [22]:
LA.norm(a, ord=2)

3.1622776601683795

In [24]:
LA.norm(a, np.inf)

2.0

In [25]:
LA.norm(a, -np.inf)

0.0

In [26]:
LA.norm(a, ord=300)

2.0046263236843456

- 使用 `axis` 参数对矩阵计算向量范数

In [17]:
C = np.array(([[0, 1, 2],
               [1, 2, 3],
               [3, 2, 1]]))
LA.norm(C, axis=0)

array([3.16227766, 3.        , 3.74165739])

In [18]:
LA.norm(C, axis=1)

array([2.23606798, 3.74165739, 3.74165739])

In [19]:
LA.norm(C, ord=1, axis=1)

array([3., 6., 6.])

- 矩阵范数

In [28]:
LA.norm(C)

5.744562646538029

In [29]:
LA.norm(C, 'fro')

5.744562646538029

In [30]:
LA.norm(C, 2)

5.223210633932344

In [31]:
LA.norm(C, np.inf)

6.0

In [32]:
LA.norm(C, -np.inf)

3.0

- 再看矩阵条件数

$$
\kappa(A)=\|A\|\|A^{-1}\|\\[1.0em]
=\frac{\sigma_{max}(A)}{\sigma_{min}(A)}
$$

矩阵的条件数用于界定一个矩阵是`良态的`还是`病态的`，一般来说，条件数越大，矩阵越接近一个奇异矩阵（不可逆矩阵），矩阵越`病态`。在数值计算中，矩阵的条件数越大，计算的误差越大，精度越低。

In [61]:
LA.norm(C, 'fro')*LA.norm(LA.inv(C), 'fro')

4.406336069451602e+16

In [40]:
LA.cond(C, 2)

1.4986581371025982e+16

## 矩阵奇异值分解

In [49]:
U,M,V = LA.svd(C,1,1)

In [50]:
U

array([[-0.36039049, -0.50471188, -0.78446454],
       [-0.68982216, -0.42189044,  0.58834841],
       [-0.62790452,  0.75317619, -0.19611614]])

In [51]:
V

array([[-0.49271146, -0.57356367, -0.65441588],
       [ 0.76848471,  0.06601555, -0.63645361],
       [-0.40824829,  0.81649658, -0.40824829]])

In [52]:
M

array([5.22321063e+00, 2.39124877e+00, 3.48525825e-16])

- 验证 C = U@M@V

In [55]:
U@np.diag(M)@V

array([[5.42493685e-16, 1.00000000e+00, 2.00000000e+00],
       [1.00000000e+00, 2.00000000e+00, 3.00000000e+00],
       [3.00000000e+00, 2.00000000e+00, 1.00000000e+00]])

In [56]:
U.dot(np.diag(M)).dot(V)

array([[5.42493685e-16, 1.00000000e+00, 2.00000000e+00],
       [1.00000000e+00, 2.00000000e+00, 3.00000000e+00],
       [3.00000000e+00, 2.00000000e+00, 1.00000000e+00]])

- 用奇异值计算条件数

In [53]:
M[0]/M[2]

1.4986581371025984e+16